apiVersion: apps/v1
kind: Deployment
metadata:
  name: spam-detection-api
  labels:
    app: spam-detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spam-detection
  template:
    metadata:
      labels:
        app: spam-detection
    spec:
      containers:
      - name: spam-api
        image: VOTRE_DOCKER_USER/spam-detection-api:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: spam-detection-service
spec:
  selector:
    app: spam-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
